spring.application.name=Hospito

spring.datasource.url=jdbc:mysql://localhost:3306/hospito
spring.datasource.username=root
spring.datasource.password=Vippul36@

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
